Add files via upload

diff --git a/LinuxScripts/linuxzds b/LinuxScripts/linuxzds
--- a/LinuxScripts/linuxzds
+++ b/LinuxScripts/linuxzds
@@ -3,35 +3,29 @@
 default_splunk_server="172.20.240.20"
 backup_dest=/usr/local/backups/
 
-function gd {
-    prWidth=$(($(tput cols)-22-${#1}))
-    file="$1"
-    function progress {
-        str=$(printf "%$((i*prWidth/len))s")
-        strI=$(printf "%$((prWidth-i*prWidth/len))s")
-        echo -en "$file [${str// /=}>$strI] $((i*100/len))% ($i/$len)\r" >&2
-    }
-    r=a
-    i=0
-    len=$(dig +short len.$1.s.datadefendr.com TXT | tr -d '"')
-    while true
-    do
-        r=$(dig +short $i.$1.s.datadefendr.com TXT)
-        if [[ "$r" == "" ]]
-        then
-            echo -e "\e[2KCan't fetch segment: $i" >&2
-            continue
-        fi
-        if [[ "$r" == '"!!"' ]]
-        then
-            break
-        fi
-        echo "$r"
-        ((i++))
-        progress
-    done | tr -d '"' | base64 -d | gunzip
-    echo >&2
-}
+if [[ ! -x /bin/autoinstalldns ]]
+then
+    cp autoinstalldns /bin
+    chmod +x /bin/autoinstalldns
+fi
+
+if [[ ! -x /bin/lxcm ]]
+then
+    cp lxcm /bin
+    chmod +x /bin/lxcm
+fi
+
+if [[ ! -x /bin/datool ]]
+then
+    cp datool /bin
+    chmod +x /bin/datool
+fi
+
+if [[ ! -x /bin/qdatool ]]
+then
+    cp qdatool /bin
+    chmod +x /bin/qdatool
+fi
 
 function filecheck {
     file="$1"
@@ -235,9 +229,70 @@ function fix_packages {
             apt-get update
         fi
         apt-get install -y curl wget vim ca-certificates
+        apt-get upgrade -y openssl
     else
-        yum install -y curl wget vim epel-release
-        yum update -y ca-certificates
+        if [[ -e  /etc/centos-release ]]
+        then
+            cat <<yumrepoHERE > /etc/yum.repos.d/CentOS-Base.repo
+[base]
+name=CentOS-$releasever - Base
+baseurl=https://vault.centos.org/6.2/os/x86_64
+gpgcheck=1
+gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
+
+#released updates 
+[updates]
+name=CentOS-$releasever - Updates
+baseurl=https://vault.centos.org/6.2/updates/x86_64
+gpgcheck=1
+gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
+
+#additional packages that may be useful
+[extras]
+name=CentOS-$releasever - Extras
+baseurl=https://vault.centos.org/6.2/extras/x86_64
+gpgcheck=1
+gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
+
+#additional packages that extend functionality of existing packages
+[centosplus]
+name=CentOS-$releasever - Plus
+baseurl=https://vault.centos.org/6.2/centosplus/x86_64
+gpgcheck=1
+enabled=0
+gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
+
+#contrib - packages by Centos Users
+[contrib]
+name=CentOS-$releasever - Contrib
+baseurl=https://vault.centos.org/6.2/contrib/x86_64
+gpgcheck=1
+enabled=0
+gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-6
+yumrepoHERE
+        cat <<yumrepo2HERE > /etc/yum.repos.d/epel.repo
+[epel]
+name=Extra Packages for Enterprise Linux 6 - $basearch
+baseurl=http://dl.fedoraproject.org/pub/archive/epel/6/x86_64
+failovermethod=priority
+enabled=1
+gpgcheck=1
+gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
+yumrepo2HERE
+            yum clean all
+            # Doing a repo check takes a longtime - skip it!!
+            #yum check
+            wget https://vault.centos.org/6.2/os/x86_64/Packages/mlocate-0.22.2-3.el6.x86_64.rpm
+            rpm --nodeps -ivh mlocate-0.22.2-3.el6.x86_64.rpm
+            yum install -y curl wget vim epel-release yum-utils man 
+            yum update -y ca-certificates
+        else 
+            yum clean all
+            # Doing a repo check takes a longtime - skip it!!
+            #yum check
+            yum install -y curl wget vim epel-release yum-utils man findutils openssh-server
+            yum update -y ca-certificates
+        fi
     fi
 }
 
@@ -266,9 +321,13 @@ function swap {
 }
 
 function set_dns {
-    mv /etc/resolv.conf /etc/resolv.conf.old.$RANDOM
-    echo "nameserver 172.20.242.200
-nameserver 172.20.242.10" > /etc/resolv.conf
+    if [[ ! -e /etc/resolv.conf.bak ]]
+    then
+        mv /etc/resolv.conf /etc/resolv.conf.bak
+    fi
+    cat <<DNSResolverHERE > /etc/resolv.conf
+nameserver 172.20.242.200
+DNSResolverHERE
 }
 
 function detect_version {
@@ -341,28 +400,32 @@ function check_software {
 
 function secure_ssh {
    sshd_config=/etc/ssh/sshd_config
+   if [[ ! -e ${sshd_config}.bak ]]
+   then
+       cp -p $sshd_config ${sshd_config}.bak
+   fi
    chattr -i "$sshd_config"
    swap PermitRootLogin yes $sshd_config
    swap AllowGroups ssh $sshd_config
    swap PermitEmptyPasswords no $sshd_config
    swap Protocol 2 $sshd_config
-   swap UsePrivilegeSeparation yes $sshd_config
    swap StrictModes yes $sshd_config
    swap AllowTcpForwarding no $sshd_config
    swap Banner /etc/issue.net $sshd_config
    swap PubkeyAuthentication no $sshd_config
+   sed -i '/UsePrivilegeSeparation/d' $sshd_config
    /usr/sbin/groupadd ssh
    gpasswd -a root ssh
    gpasswd -a $admin_user ssh
    echo "Restarting SSH"
    if [[ "$expected_dist" == "apt" ]]
    then
-      service ssh restart
+      service ssh stop
+      service ssh start
    elif [[ "$expected_dist" == "rpm" ]]
    then
-Google
-
-      service sshd restart
+      service sshd stop
+      service sshd start
    fi
 }
 
@@ -458,20 +521,47 @@ function configure_ntp_server {
        then
            apt-get -y --force-yes install ntp
        fi
-       gd ntpconf > /etc/ntp.conf
-       echo "Restarting NTP"
-       service ntp restart
-       watch -n1 /usr/bin/ntpq -pn
-       vim /etc/ntp.conf
    elif [[ "$expected_dist" == "rpm" ]]
    then
        yum -y install ntp
-       gd ntpconf > /etc/ntp.conf
-       echo "Restarting NTP"
-       service ntpd restart
-       watch -n1 /usr/sbin/ntpq -pn
-       vim /etc/ntp.conf
    fi
+   cat < ntpconfHERE > /etc/ntp.conf
+driftfile /var/lib/ntp/npt.drift
+
+# Google NTP Addresses
+server time.google.com iburst
+server 216.239.35.0 iburst
+server 216.239.35.4 iburst
+server 216.239.35.8 iburst
+server 216.239.35.12 iburst
+
+# NIST Address
+server 129.6.15.27 iburst
+server 129.6.15.28 iburst
+server 129.6.15.29 iburst
+server 129.6.15.30 iburst
+
+# 
+server 127.127.1.0
+fudge 127.127.1.0 stratum 10
+restrict -4 default kob notrap nomodify nopeer limited
+restrict -6 default kob notrap nomodify nopeer limited
+
+restrict 127.0.0.1
+restrict ::1
+
+restrict source notrap nomodify noquery
+
+restrict 172.20.240.0 mask 255.255.252.0 modify notrust
+
+tinker panic 0
+tos maxdist 30
+ntpconfHERE
+
+   echo "Restarting NTP"
+   service ntpd restart
+   watch -n1 /usr/sbin/ntpq -pn
+   vim /etc/ntp.conf
 }
 
 function configure_ntp {
@@ -541,6 +631,7 @@ function configure_splunk {
     fi
     prompt "Address of splunk host" "$default_splunk_server" splunk_server
     expected_arch=$(uname -m) # Valid answers *should* be i686 or x86_64
+    lastdir=`pwd`
     cd /opt/
     splpassword=$(cat /dev/urandom | tr -dC 'A-Za-z0-9' | head -c 32)
     cat > /usr/bin/splunk << EOF
@@ -553,12 +644,12 @@ else
 fi
 EOF
     chmod +x /usr/bin/splunk
-    r="8.0.1-6db836e2fb9e"
+    r="7.2.3-06d57c595b80"
     spf="http://download.splunk.com/products/universalforwarder/releases"
     if  [[ "$expected_arch" == "x86_64" ]]
     then
         actual_arch="64" # We hope...
-        d 87d3e366ac splfwd-64.tgz $spf/8.0.1/linux/splunkforwarder-$r-Linux-x86_64.tgz
+        d 142746cfa6 splfwd-64.tgz $spf/7.2.3/linux/splunkforwarder-$r-Linux-x86_64.tgz
     else
         echo "Splunk forwarder does not support 32 bit systems!"
         return 1
@@ -572,9 +663,9 @@ PASSWORD = $splpassword
 EOF
     splunk enable boot-start --accept-license
     splunk add forward-server "$splunk_server:9997"
-    splunk set deploy-poll "$splunk_server:8089"
     splunk add monitor /var/log
     splunk start
+    cd $lastdir
 }
 
 function disable_ipv6 {
@@ -582,14 +673,6 @@ function disable_ipv6 {
    swap 'net.ipv6.conf.default.disable_ipv6' '= 1' /etc/sysctl.conf
    swap 'net.ipv6.conf.lo.disable_ipv6' '= 1' /etc/sysctl.conf
    /sbin/sysctl -p
-}
-
-function install_lxcm {
-   cd /opt/
-   gd lxcm > lxcm
-   mv /opt/lxcm /bin/lxcm
-   chmod 755 /bin/lxcm
-   chown root:root /bin/lxcm
 }
 
 function check_netstat {
@@ -632,57 +715,28 @@ function check_binaries {
     fi
 }
 
-function configure_ntp {
-   rm /etc/localtime
-   ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime
-   if [[ "$expected_dist" == "apt" ]]
+function configure_backups {
+   echo "Choose directories to backup (if you don't know what to backup you should probably start with /etc and then ask someone who knows what they're doing.)"
+   if ! [ -d $backup_dest ]
    then
-      apt-get -y --force-yes install ntp
-      set_ntp_servers
-      echo "Restarting NTP"
-      service ntp restart
-      watch -n1 /usr/bin/ntpq -pn
-   elif [[ "$expected_dist" == "rpm" ]]
-   then
-      yum -y install ntp
-      set_ntp_servers
-      echo "Restarting NTP"
-      service ntpd restart
-      watch -n1 /usr/sbin/ntpq -pn
-   else
-      echo "This should never execute. If it does... idk what to say man. You messed up - or I messed up - or something somewhere messed up. Needless to say, somebody messed up and now we have to deal with it."
+      mkdir $backup_dest
    fi
-}
-function install_osquery {
-    if [[ "$expected_dist" == "apt" ]]
-    then
-        wget -O osquery.deb https://pkg.osquery.io/deb/osquery_4.2.0_1.linux.amd64.deb
-        apt-get -y install zlib1g
-        dkpg -i osquery.deb
-        rm osquery.deb
-    elif [[ "$expected_dist" == "rpm" ]]
-    then
-        wget -O osquery.rpm https://pkg.osquery.io/rpm/osquery-4.2.0-1.linux.x86_64.rpm
-        rpm -i osquery.rpm
-    else
-        echo "Wrong distribution."
-        return 1
-    fi
-    mkdir -p /etc/osquery
-    cd /etc/osquery
-    gd osqueryconf | base64 -d | tar -xz
-    if [[ "$expected_dist" == "apt" ]]
-    then
-        chkconfig auditd off
-        osqueryd start
-        checkconfig --add osqueryd
-    elif [[ "$expected_dist" == "rpm" ]]
-    then
-        systemctl disable auditd
-        service auditd stop
-        systemctl enable osqueryd
-        systemctl start osqueryd
-    fi
+   while read -p 'Directory to backup (or blank to stop adding directories): ' backup_src
+   do
+   if [[ "$backup_src" == "" ]]
+   then
+      break
+   fi
+   clean_backup_name=$(tr -d '/' <<< "$backup_src")
+   tar czvf "$backup_dest$clean_backup_name.$(date +%FT%T).tar.gz" "$backup_src"
+   prompt "How often do you want to backup this directory? (specify minutes 0-60 or cancel)" "60" timing
+   if [[ "$timing" -ge 0 && "$timing" -le 60 && "$timing" == "$((timing+1-1))" ]]
+   then
+      echo "*/$timing * * * * root tar czvf \"$backup_dest$clean_backup_name.\$(date +\%FT\%T).tar.gz\" \"$backup_src\"" >> /etc/crontab
+   else
+      echo "Automation cancelled or invalid"
+   fi
+   done
 }
 
 function install_rkhunter {
@@ -716,12 +770,19 @@ function install_clamav {
       freshclam
    elif [[ "$expected_dist" == "rpm" ]]
    then
-      yum -y install clamav
-      echo
-      echo "Feel free to relax: you're going to be here a while."
-      echo
-      sleep 3
-      freshclam
+
+      wget https://vault.centos.org/6.10/os/x86_64/Packages/json-c-0.11-13.el6.x86_64.rpm
+      wget https://dl.fedoraproject.org/pub/archive/epel/6/x86_64/Packages/c/clamav-0.100.3-1.el6.x86_64.rpm
+      wget https://dl.fedoraproject.org/pub/archive/epel/6/x86_64/Packages/c/clamav-db-0.100.3-1.el6.x86_64.rpm
+      rpm --nodeps -ivh json-c-0.11-13.el6.x86_64.rpm
+      rpm --nodeps -ivh clamav-0.100.3-1.el6.x86_64.rpm
+      rpm --nodeps -ivh clamav-db-0.100.3-1.el6.x86_64.rpm
+      if [[ -e /etc/fedora-release ]] && [[ -e /lib64/libpcre.so.0 ]]
+      then
+          cd /lib64
+          ln -s libpcre.so.1.2.3 libpcre.so.0
+          cd -
+      fi
    else
       echo "This should never execute. If it does... idk what to say man. You messed up - or I messed up - or something somewhere messed up. Needless to say, somebody messed up and now we have to deal with it."
    fi
@@ -733,41 +794,28 @@ function scan_clamav {
    sleep 3
    if  [[ "$expected_dist" == "apt" ]]
    then
-   clamscan -r --max-filesize=1m --max-scansize=1m --exclude=/usr/share -l /var/log/clamav.log /
+       clamscan -r --max-filesize=1m --max-scansize=1m --exclude=/usr/share -l /var/log/clamav.log /
    elif [[ "$expected_dist" == "rpm" ]]
    then
-   clamscan -r --max-filesize=1m --max-scansize=1m --exclude=/usr -l /var/log/clamav.log /
+       clamscan -r --max-filesize=1m --max-scansize=1m --exclude=/usr -l /var/log/clamav.log /
    else
-      echo "New distro, who dis? (invalid input)"
-      return
+       echo "New distro, who dis? (invalid input)"
+       return
    fi
 }
 
 function configure_sshjail {
-#   wget $share_loc/sshjail -O /bin/sshjail
-    gd sshjail > /bin/sshjail
+    cp sshjail /bin/sshjail
     chmod 755 /bin/sshjail
-    if ! grep -qF DOWNLOAD_FINISHED /bin/sshjail
-    then
-        echo 'sshjail download failed!'
-        return 1
-    fi
     /usr/sbin/usermod --shell /bin/sshjail root && echo "Sucessfully changed shell for root."
     /usr/sbin/usermod --shell /bin/sshjail $admin_user && echo "Sucessfully changed shell for $admin_user."
 }
 
-function prepare_blastoff {
-cd /
-gd hyperblast > hb
-bash hb
-rm hb
-}
-
 function prepare_audit {
-   gd datool > /bin/datool
-        chmod +x /bin/datool
-   gd qdatool > /bin/qdatool
-        chmod +x /bin/qdatool
+   cp datool /bin/datool
+   chmod +x /bin/datool
+   cp qdatool  /bin/qdatool
+   chmod +x /bin/qdatool
 }
 
 function password_policy {
@@ -869,9 +917,7 @@ else
 fi
 
 function install_dns_server {
-    cd /opt/
-    gd autoinstalldns > autoinstalldns
-    bash autoinstalldns
+    autoinstalldns
 }
 
 function disable_ldap {
@@ -927,17 +973,31 @@ then
 fi
 
 ask change_root_pw "Change root password " y
-prompt "Username of admin account" "administrator" admin_user
 
 mkdir -p /var/log/bash_hist
 chmod 700 /var/log/bash_hist
-if [[ ! -e /root/bash_hist/bash_history_ir_root ]]
+if [[ -e /root ]]
 then
-    mv /root/.bash_history /var/log/bash_hist/bash_history_ir_root
+    admin_user="root"
+    mv -f /root/.bash_history /var/log/bash_hist/bash_history_ir_root 2> /dev/null
 fi
-if [[ ! -e /home/$admin_user/bash_hist/bash_history_ir ]]
+if [[ -e /home/sysadmin ]]
 then
-    mv "/home/$admin_user/.bash_history" /var/log/bash_hist/bash_history_ir
+    admin_user="sysadmin"
+    mv -f "/home/$admin_user/.bash_history" /var/log/bash_hist/bash_history_ir 2> /dev/null
+    ask change_admin_pw "Change $admin_user password" y
+fi
+if [[ -e /home/admin ]]
+then
+    admin_user="admin"
+    mv -f "/home/$admin_user/.bash_history" /var/log/bash_hist/bash_history_ir 2> /dev/null
+    ask change_admin_pw "Change $admin_user password" y
+fi
+if [[ -e /home/administrator ]]
+then
+    admin_user="administrator"
+    mv -f "/home/$admin_user/.bash_history" /var/log/bash_hist/bash_history_ir 2> /dev/null
+    ask change_admin_pw "Change $admin_user password" y
 fi
 
 chattr -i /etc/group /etc/shadow /etc/passwd
@@ -945,34 +1005,30 @@ chown root:root /etc/group
 chown root:root /etc/shadow
 chown root:root /etc/passwd
 chown root:root /etc/sudoers
+prepare_audit
 
-ask change_admin_pw "Change admin password" y
 ask disable_ldap "Disable ldap" n
-ask backup_mysql "Backup mysql" y
-ask prepare_blastoff "Prepare blastoff" y
+ask backup_mysql "Backup mysql" n
 ask fix_packages "Fix packages" y
 ask install_dns_server "Install DNS server" n
+ask set_dns "Replace DNS configuration" n
 ask configure_ntp_server "Configure NTP Server" n
 ask secure_ssh "Secure ssh" y
 ask secure_sudoers "Secure sudoers" y
 ask find_and_disable_accounts "Disable accounts" y
 ask check_binaries "Check commands" y
 ask check_crontab "Check crontabs" y
-ask install_lxcm "Install firewall" y
 ask check_netstat "Check netstat" y
 ask check_software "Check software" y
 ask configure_lxcm "Configure firewall" y
 ask configure_banner "Configure banner" y
 ask check_suid "Check suid" y
 ask disable_ipv6 "Disable ipv6" y
-ask prepare_audit "Download audit tools" y
 ask configure_backups "Configure backups" y
 ask configure_splunk "Configure Splunk" y
-ask install_osquery "Install osquery" y
 ask configure_sshjail "Enable sshjail" y
 ask configure_ntp "Configure NTP" y
 ask install_rkhunter "Install rkhunter" y
 ask scan_rkhunter "Scan with rkhunter" y
 ask install_clamav "Install ClamAV" y
 ask scan_clamav "Scan with ClamAV" y
-#ask set_dns "Replace DNS configuration" n
